### ISSUE TITLE
Invoicing improvements

### ISSUE THREAD

**Issue by MrNaif2018** [bitcart/bitcart#162]
This issue contains a list of improvements in invoicing area (invoice creation/checkout policies and new features):

- [x] Add a button at stores page to easily see invoices associated with a store (via improved search, see #169)
- [x] <strike>Add store website setting back, and display it on checkout (after successful checkout, "Return to store" button can be clicked to return to store site OR admin instance)</strike> No use
- [x] <strike>Add more consistent UI of expired/paid invoices, possibly not changing the dialog size (display the check mark inside the component where scan/copy tabs are displayed, and not instead of the whole checkout dialog)</strike> It's fine
- [x] Fix an issue with scrollbars appearing sometimes on expired/complete invoices (possibly related to a css animation; a more consistent UI might fix this issue)
- [x] For store POS privacy, use non-integer id's (see #169 for more information)
- [ ] Improve privacy of endpoints, make store POS access invoices, stores and products endpoints without making those endpoints publicly available (possibly via pre-authorization, we can use docker volumes to share a "cookie" file with credentials for the store)
- [ ] Integrate some services for inter-currency conversion? (via plugins system)
- [x] Improve checkout rates handling, allow changing rate provider from the UI, add ability to try out (and get rates for information purposes) the exchange rates right from the UI
- [x] Add a store policy to make customer email optional in the store POS. 
- [x] Add a dialog in the admin's checkout modal to enter an email.
- [x] Internationalization, i18n (see #168)
- [x] Add ability to customize the look of the checkout page in detail (possibly via vuetify exported color css variables, see #166)
- [ ] Add ability to easily integrate a payment button to some store (for users to not implement it manually), with a variety of configuration options
- [x] Possibly list possible integrations/display connected integrations (WooCommerce, WHMCS) and display revelant docs links
- [ ] Crowdfunding support
- [x] Refunds support
- [x] Amount paid detection (#152)
- [ ] Recurring payments support (#174)
- [x] Add ability for customers to add additional notes to invoices

**Comment by MrNaif2018** [comment]
All important issues were moved to subissues or has been resolved already
