### ISSUE TITLE
Hacktoberfest welcome

### ISSUE THREAD

**Issue by MrNaif2018** [bitcart/bitcart#243]
This month [Hacktoberfest](https://hacktoberfest.digitalocean.com/) is held!
We welcome all new and existing contributors, this issue is a list of all issues from BitcartCC projects (new features, bug fixes, etc.)
If you have any questions regarding the project, open an issue on github or contact us in our [communities](https://bitcartcc.com/#community).
More information on the project itself is available on our official [website](https://bitcartcc.com) and [documentation](https://docs.bitcartcc.com)

We now have our [roadmap](https://github.com/orgs/bitcartcc/projects/1) set up for long-term BitcartCC development. You can check the issue lists from the roadmap and try implementing some of the tasks from them. Each task in a tasklist can be done in a separate PR, there are lots of things to do! The descriptions in the list are not always complete, if you want to start working on some feature and want a detailed explanation, comment on the selected task list and I will open a separate issue describing that task.

Issue list:

bitcart repository:
- [x] #247 
- [x] #251 
- [x] #105 
- [x] #152 
- [x] #160 
- [x] #161 
- [x] #162 
- [x] #163 
- [x] #164 
- [x] #165 
- [x] #166 
- [x] #167 
- [x] #168 
- [x] #169 
- [ ] #174 
- [x] #218 
- [x] #235 
- [x] #242
- [x] #244

bitcart-admin repository:
- [ ] Admin issue list bitcartcc/bitcart-admin#120

bitcart-store repository:
- [ ] Store issue list bitcartcc/bitcart-store#317

bitcart-site repository:
- [ ] Site issue list bitcartcc/bitcart-site#84

bitcart-blog repository:
- [ ] Blog issue list bitcartcc/bitcart-blog#111

bitcart-docs repository:
- [ ] Docs issue list bitcartcc/bitcart-docs#5

**Comment by MrNaif2018** [comment]
Thanks to everyone who has contributed to BitcartCC this hacktoberfest! You are welcome to contribute any time of the year of course!
